name: Check if version in pyproject.toml matches version in __init__.py
description: Action checks if version in pyproject.toml matches version in __init__.py
inputs:
  github_token:
    description: Token, to read the GitHub API. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    required: true
runs:
  using: docker
  image: Dockerfile
