name: Release what-to-eat to PyPI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.12.0"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
